### PR TITLE
Changed the reference from unzip2 to node-unzip-2 (same library) 

### LINKED ISSUE #1: Not working on Node 12 & 13 due to node-unzip2.
Hi, we recently bumped our projects to use Node 12.
When trying to pull our features from Jira, we're seeing this error
`npx behavepro --output acceptance_tests/behaveProFeatures --config behavepro.config.json
primordials is not defined`

I've had a look and this seems to be linked to node-unzip2 not supporting node versions 12 & 13: https://github.com/glebdmitriew/node-unzip-2/issues/28

If I have some time over the weekend I will try and put a PR in to fix this.

### PR DESCRIPTION
**Pull request by james-w-arnold**
To allow for node 12 & 13 support).
Tested with Node v12.13.0

Fixed: https://github.com/hindsightsoftware/behave-pro-node/issues/1

### CODE REVIEW

**Comment by JonHX** [comment]
Would love to see this fixed 👍

**Review by RyanD1996 — APPROVED** [review]
This is the change we need, great moves keep it up.

**Comment by aparkinson** [comment]
Thank you @james-w-arnold for the work on this

**Comment by aparkinson** [comment]
We have an [upcoming webinar](https://zoom.us/webinar/register/WN_z1Yh2LkzRFmzPzSWB-zbtQ) on how Behave Pro can publish to Git instead of the builds tools. It might be of interest to everyone

**Comment by aparkinson** [comment]
The change has now been published. Thank you for your contribution!

**Comment by james-w-arnold** [comment]
No worries :) Happy to help

**Pull request merged**
